# Generated by Django 3.2.9 on 2021-11-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col', models.CharField(max_length=10)),
            ],
        ),
    ]
